development:
  adapter: mysql2
  database: development
  username: root
  password: 
  host: localhost
test:
  adapter: mysql2
  database: test
  username: root
  password: 
  host: localhost
production:
  adapter: mysql2
  database: production
  username: root
  password: 
  host: localhost

